/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.modules.async;

import org.mule.api.annotations.Module;
import org.mule.api.annotations.Processor;
import org.mule.api.annotations.param.Default;
import org.mule.api.annotations.param.Optional;

/**
 * Cloud Connector
 *
 * @author MuleSoft, Inc.
 */
@Module(name = "http-client", description = "Async Http Connector", friendlyName = "Async Http Connector", schemaVersion = "1.0-SNAPSHOT")
public class HttClientConnector
{

    /**
     *
     * Execute get method over http
     *
     * {@sample.xml ../../../doc/async-http-client-connector.xml.sample http-client:get}
     * @param uri The uri
     * @return The execution result
     */
    @Processor(asynch = true)
    public Object get(@Optional @Default(value = "#[payload]") String uri){

        return null;

    }

}
